### PR TITLE
remove identity-box padding

### PR DESCRIPTION
**Pull request by ghost**
It appears that `#identity-box` has a top and bottom padding which causes the nav-bar height to suddenly increase when switching to a tab with a site identity label. This pull request removes the padding from this element.

### CODE REVIEW

**Comment by traxium** [comment]
Could you give a link to a site that has an identity label causing this problem? It's the first time I hear about this bug.

**Comment by ghost** [comment]
https://github.com :smile:

For me, it's any site that has an identity label.

**Comment by traxium** [comment]
Sorry. I couldn't confirm this bug. And I didn't see that anybody else mentioned this bug.
And also my reasoning why: #identity-box is inside #urlbar but this add-on doesn't change the height of #urlbar. The height of #urlbar is always the same regardless whether Navigation Bar height is 24px or 38px.
And besides that your PR doesn't go well with the dark Firefox theme on every OS:
github - identity-box - not maximized

**Comment by ghost** [comment]
Ok it might be an issue with how Firefox GTK+. I've fixed it on my end with a user-style. I'll close this. Thanks for trying to confirm it.

**Pull request closed without merging**
