### PR TITLE
Makes the autohide key customizable.

### PR DESCRIPTION
**Pull request by MichelTenVoorde**
Translations for non-English locales needed.

### CODE REVIEW

**Comment by MichelTenVoorde** [comment]
Sorry for the lack of information and/or documentation, this is the first time I'm doing something like this. Hope it all makes sense.

I use F8 a lot to go to Firefox's address bar, and I was getting frustrated with the same keystroke hiding the tab pane. This is a quick fix that works for me, though a 'free text' input has its cons, naturally. I'd consider it an expert option. I'm not sure what the syntax is for keys in general either.

I could live with declining this pull request, and change the hotkey to F9, which I think does nothing by default in Firefox.

**Comment by dkasak** [comment]
What's preventing this to merge?

**Comment by Luckz** [comment]
F8 doesn't go to my address bar, is this an addon you use? :)

**Comment by traxium** [comment]
Sorry, I'll merge it later.

**Comment by MichelTenVoorde** [comment]
@Luckz, you're totally right, I completely forgot about that. Former Opera user here, so I guess the first thing I did was find an addon to enable some shortcuts I was used to.

**Pull request merged**
